/**
 * CoreMind Knowledge Base.
 * Each entry has: id, category, question (canonical), aliases (alt phrasings), answer, tags.
 * Retrieval engine matches against question + aliases + tags using fuzzy + synonym expansion.
 */

export interface KBEntry {
  id: string
  category: string
  question: string
  aliases?: string[]
  answer: string
  tags?: string[]
}

export const KNOWLEDGE_BASE: KBEntry[] = [
  // ============ AZIENDA / GENERALE ============
  {
    id: 'company-1',
    category: 'Azienda',
    question: "Cos'è Ecosystem?",
    aliases: ['chi siete', 'cosa fate', 'di cosa vi occupate', 'cosa è ecosystem', 'che cos\'è'],
    answer: "Ecosystem è la piattaforma AI-native multi-verticale italiana che riunisce 13 suite gestionali specializzate (edilizia, legale, dentale, ristorazione, retail, immobiliare, IT, PA, veterinaria, ittico, e altre) in un unico ecosistema, costruito intorno a CoreMind — l'intelligenza artificiale nativa che capisce la tua azienda. Made in Italy, sviluppata da Ecosystem S.R.L.",
    tags: ['azienda', 'piattaforma', 'overview'],
  },
  {
    id: 'company-2',
    category: 'Azienda',
    question: "Chi è il fondatore di Ecosystem?",
    aliases: ['founder', 'amministratore', 'ceo', 'chi ha creato'],
    answer: "Il fondatore è **Giuseppe Mignano**, con 7+ anni di consulenza aziendale e 37 progetti gestiti per oltre €50M di valore. Co-founder: **Salvatore Brancaccio** (CFO, Direttore Amministrativo) e **Claudia Del Giudice** (CCO, Direttore Marketing). Il team include anche **Danilo Mastrocola** (DevOps Engineer / Sviluppatore).",
    tags: ['team', 'azienda'],
  },
  {
    id: 'company-3',
    category: 'Azienda',
    question: "Dove ha sede Ecosystem?",
    aliases: ['sede', 'indirizzo', 'ufficio', 'dove siete'],
    answer: "Sede legale: Via Pietrerotte 13, 81037 Sessa Aurunca (CE). Sede operativa: Santi Cosma e Damiano (LT). P.IVA 04910300617 · REA CE-365391. PEC: ecosystem@pec.it.",
    tags: ['contatti', 'sede'],
  },
  {
    id: 'company-4',
    category: 'Azienda',
    question: "Come posso contattarvi?",
    aliases: ['contatti', 'email', 'telefono', 'numero', 'come scrivervi'],
    answer: "Puoi contattarci tramite:\n- **Email**: info@ecosystem.org\n- **Telefono**: +39 327 160 4592\n- **PEC**: ecosystem@pec.it\n- **Form contatti**: [/contatti](/contatti)\n\nRispondiamo entro 24h lavorative. Per richieste demo, prenota direttamente dal form e ti chiamiamo entro 1 giorno.",
    tags: ['contatti'],
  },
  {
    id: 'company-5',
    category: 'Azienda',
    question: "Ecosystem è italiana?",
    aliases: ['made in italy', 'azienda italiana', 'italiano'],
    answer: "Sì, Ecosystem è 100% Made in Italy. Sviluppata in Italia, hosting su data center italiani certificati ISO 27001 / ISO 22301 / Tier IV, supporto in italiano, conformità GDPR e normativa nazionale.",
    tags: ['italia', 'made in italy'],
  },

  // ============ COREMIND / AI ============
  {
    id: 'coremind-1',
    category: 'CoreMind',
    question: "Cos'è CoreMind?",
    aliases: ['ai', 'intelligenza artificiale', 'assistente', 'chatbot'],
    answer: "CoreMind è l'intelligenza artificiale nativa di Ecosystem. È un assistente AI integrato in tutta la piattaforma che capisce il linguaggio naturale, esegue azioni operative ('crea ordine fornitore', 'genera SAL', 'fattura del Q3') e impara dai processi della tua azienda. Funziona su ogni suite e ha accesso ai dati del tuo gestionale (con i tuoi permessi).",
    tags: ['ai', 'coremind'],
  },
  {
    id: 'coremind-2',
    category: 'CoreMind',
    question: "Quali modelli AI usa CoreMind?",
    aliases: ['gpt', 'claude', 'llm', 'modello'],
    answer: "Il piano Professional usa modelli commerciali (Anthropic Claude, OpenAI GPT) con contratti zero-retention firmati: i tuoi dati non trainano i modelli. Il piano Enterprise può usare modelli on-premise o privati (Llama, Mistral) ospitati sui tuoi server. Configurazione personalizzabile.",
    tags: ['ai', 'modelli', 'privacy'],
  },
  {
    id: 'coremind-3',
    category: 'CoreMind',
    question: "CoreMind condivide i miei dati con OpenAI o Anthropic?",
    aliases: ['privacy ai', 'dati ia', 'training'],
    answer: "Solo se tu lo scegli. Il piano Professional usa modelli commerciali con contratti zero-retention firmati (i tuoi dati non trainano i modelli). Il piano Enterprise può usare modelli on-premise che non escono mai dai tuoi server. Hai sempre il controllo.",
    tags: ['privacy', 'ai'],
  },
  {
    id: 'coremind-4',
    category: 'CoreMind',
    question: "Quante interazioni AI sono incluse?",
    aliases: ['quante query', 'limiti ai', 'interazioni'],
    answer: "Le query CoreMind incluse dipendono dal piano:\n- **Starter**: 500 query/mese\n- **Professional**: 5.000 query/mese\n- **Enterprise**: illimitate\n\nOltre soglia: €0.012/query. Le query non utilizzate non si cumulano tra mesi.",
    tags: ['limiti', 'pricing'],
  },

  // ============ PREZZI ============
  {
    id: 'pricing-1',
    category: 'Prezzi',
    question: "Quanto costa Ecosystem?",
    aliases: ['prezzi', 'costi', 'tariffe', 'listino', 'piano', 'piani', 'investimento', 'budget'],
    answer: "Ecosystem ha 3 piani:\n- **Starter** — da €49/mese + setup, ideale per piccole aziende\n- **Professional** — da €129/mese + setup, multi-utente con CoreMind avanzato\n- **Enterprise** — su preventivo, multi-entity, on-premise, SLA contrattuale\n\nVai su [/pricing](/pricing) per il calcolatore ROI e tutti i dettagli. Nessuna fee nascosta, canone definito.",
    tags: ['pricing', 'piani'],
  },
  {
    id: 'pricing-2',
    category: 'Prezzi',
    question: "Cosa include il piano Starter?",
    aliases: ['starter', 'piano base', 'base'],
    answer: "Il piano **Starter** include: 1 suite a scelta, fino a 5 utenti, CoreMind base (500 query/mese), email support (SLA 48h), 1h/mese di assistenza inclusa, hosting cloud Italia, backup giornaliero. Setup una tantum personalizzato. Da €49/mese.",
    tags: ['starter', 'piani'],
  },
  {
    id: 'pricing-3',
    category: 'Prezzi',
    question: "Cosa include il piano Professional?",
    aliases: ['professional', 'piano pro', 'professionale'],
    answer: "Il piano **Professional** include: tutte le suite attivabili, utenti illimitati, CoreMind Pro (5.000 query/mese), supporto multicanale (email, chat, telefono — SLA 4h lavorative / 8h h24), 4h/mese di assistenza, integrazioni native, audit log, SSO base. Da €129/mese.",
    tags: ['professional', 'piani'],
  },
  {
    id: 'pricing-4',
    category: 'Prezzi',
    question: "Cosa include il piano Enterprise?",
    aliases: ['enterprise', 'aziendale', 'grande azienda'],
    answer: "Il piano **Enterprise** è su preventivo e include: utenti illimitati multi-tenant, SSO SAML 2.0/OIDC/Active Directory, audit log esteso (retention 7 anni), SLA 99.9% contrattuale con penali, self-hosted o cloud privato (AWS / Azure / OVH), on-site training, integrazioni custom illimitate, penetration test annuale, account manager dedicato. SLA 1h lavorative / 4h h24 con escalation. 16h/mese di assistenza incluse.",
    tags: ['enterprise', 'piani'],
  },
  {
    id: 'pricing-5',
    category: 'Prezzi',
    question: "Posso pagare a consumo?",
    aliases: ['pay per use', 'pagamento variabile', 'a consumo'],
    answer: "I canoni sono fissi per utenti/funzioni base. A consumo paghi solo: query CoreMind oltre soglia (€0.012/query), storage extra oltre quota piano, ore di assistenza extra (€90/h piano Professional, €150/h Enterprise). Tutto trasparente, tracciato in dashboard.",
    tags: ['pricing'],
  },
  {
    id: 'pricing-6',
    category: 'Prezzi',
    question: "Quanto costa il setup?",
    aliases: ['setup', 'fee iniziale', 'attivazione', 'una tantum'],
    answer: "Il setup è una tantum, calcolato sulla complessità: importazione dati, configurazione moduli, formazione team. Indicativi: Starter €490–€1.500, Professional €2.000–€8.000, Enterprise €15.000–€80.000. Sul calcolatore [/pricing](/pricing) hai una stima precisa in 30 secondi.",
    tags: ['setup', 'pricing'],
  },
  {
    id: 'pricing-7',
    category: 'Prezzi',
    question: "Ci sono sconti annuali?",
    aliases: ['sconto', 'risparmio', 'pagamento annuale', 'fatturazione annuale'],
    answer: "Sì: **-10% sul canone con pagamento annuale anticipato** (in unica soluzione). Possibile anche fatturazione trimestrale. Disdetta libera dopo i primi 12 mesi con preavviso di 60 giorni. Per Enterprise contratti pluriennali con sconti dedicati.",
    tags: ['sconto', 'pricing'],
  },
  {
    id: 'pricing-8',
    category: 'Prezzi',
    question: "C'è un periodo di prova gratuito?",
    aliases: ['trial', 'gratis', 'prova gratuita', 'free trial'],
    answer: "Sì: **demo interattiva gratuita** su [/demo](/demo) — 4 suite in modalità sandbox con dati finti ma funzioni reali, CoreMind attivo, nessuna registrazione. Per una prova personalizzata sui tuoi dati: 14 giorni di trial Professional su richiesta a info@ecosystem.org.",
    tags: ['demo', 'trial'],
  },
  {
    id: 'pricing-9',
    category: 'Prezzi',
    question: "Posso cambiare piano in corso?",
    aliases: ['upgrade', 'downgrade', 'cambiare piano'],
    answer: "Sì, in qualsiasi momento. **Upgrade**: immediato, paghi solo la differenza prorata. **Downgrade**: effettivo dal mese successivo. I tuoi dati restano identici. Passare da Starter a Professional richiede solo un click, senza downtime.",
    tags: ['upgrade', 'piani'],
  },
  {
    id: 'pricing-10',
    category: 'Prezzi',
    question: "Le iva è inclusa nei prezzi?",
    aliases: ['iva', 'tasse'],
    answer: "No, tutti i prezzi indicati sono **iva esclusa**. Il setup è pagabile alla firma del contratto. Il canone mensile può essere fatturato anticipato in unica soluzione annuale (-10%) oppure trimestrale.",
    tags: ['iva', 'fatturazione'],
  },

  // ============ DEMO ============
  {
    id: 'demo-1',
    category: 'Demo',
    question: "Posso provare Ecosystem prima di acquistarlo?",
    aliases: ['demo', 'prova', 'test', 'trial'],
    answer: "Assolutamente sì. Su [/demo](/demo) hai 4 suite in modalità interattiva (BuildSuite, LegalMind, DentalSuite, FoodSuite) con dati finti ma funzioni reali e CoreMind attivo. Cinque minuti per capire esattamente cosa fa Ecosystem. Nessuna registrazione, nessun download.",
    tags: ['demo'],
  },
  {
    id: 'demo-2',
    category: 'Demo',
    question: "La demo è gratuita?",
    aliases: ['demo gratis', 'prova gratis'],
    answer: "Sì, la demo interattiva è 100% gratuita e non richiede registrazione. Apri [/demo](/demo), scegli la suite del tuo settore e iniziamo subito. Per una demo personalizzata sui tuoi processi, prenota una call su [/contatti](/contatti).",
    tags: ['demo', 'free'],
  },
  {
    id: 'demo-3',
    category: 'Demo',
    question: "Posso prenotare una demo personalizzata?",
    aliases: ['demo live', 'demo guidata', 'video call'],
    answer: "Sì. Su [/contatti](/contatti) prenoti una call di 30 minuti con il nostro team. Ti mostriamo Ecosystem configurato sul tuo settore, rispondiamo alle tue domande e ti diamo un'analisi gratuita su come migliorare i tuoi processi.",
    tags: ['demo', 'meeting'],
  },

  // ============ SUITE ============
  {
    id: 'suite-build',
    category: 'Suite',
    question: "Cos'è BuildSuite?",
    aliases: ['edilizia', 'cantieri', 'costruzioni', 'buildsuite'],
    answer: "**BuildSuite** è la suite per edilizia e cantieri. Include: gestione cantieri multipli, SAL automatici, sicurezza POS/PSC, controllo costi e margini, scadenzario manodopera, integrazione AutoCAD/Revit/PriMus/ACCA, fotografie cantiere geolocalizzate. Da €49/mese.",
    tags: ['edilizia', 'cantieri'],
  },
  {
    id: 'suite-legal',
    category: 'Suite',
    question: "Cos'è LegalMind?",
    aliases: ['studio legale', 'avvocato', 'legalmind', 'legale'],
    answer: "**LegalMind** è la suite per studi legali. Include: pratiche, scadenzari processuali, parcelle e fatturazione, deposito telematico (PCT), firma digitale, integrazione Adobe Sign / DocuSign / Aruba PEC. Da €69/mese.",
    tags: ['legale', 'avvocato'],
  },
  {
    id: 'suite-dental',
    category: 'Suite',
    question: "Cos'è DentalSuite?",
    aliases: ['dentista', 'odontoiatria', 'dentalsuite'],
    answer: "**DentalSuite** è la suite per studi odontoiatrici. Include: cartella clinica digitale, agenda multi-poltrona, preventivi e piani di cura, conformità privacy/HACCP studio, integrazione Cefla/Sirona/KaVo/Invisalign. Da €59/mese.",
    tags: ['dentista', 'odontoiatria'],
  },
  {
    id: 'suite-food',
    category: 'Suite',
    question: "Cos'è FoodSuite?",
    aliases: ['ristorante', 'ristorazione', 'foodsuite', 'horeca'],
    answer: "**FoodSuite** è la suite per ristorazione e HoReCa. Include: gestione menù, food cost real-time, conformità HACCP, integrazione delivery (Glovo, JustEat, Deliveroo, UberEats), POS Toast/Square. Da €39/mese.",
    tags: ['ristorante', 'horeca'],
  },
  {
    id: 'suite-okchef',
    category: 'Suite',
    question: "Cos'è OK Chef?",
    aliases: ['okchef', 'ok chef', 'cucina professionale', 'approvvigionamento'],
    answer: "**OK Chef** è la suite per approvvigionamento HoReCa. Include: gestione fornitori multi-canale, listini con margini, ordini automatizzati basati su consumo previsto, controllo qualità ricevimento merci.",
    tags: ['horeca', 'approvvigionamento'],
  },
  {
    id: 'suite-fish',
    category: 'Suite',
    question: "Cos'è FishSuite?",
    aliases: ['pesca', 'ittico', 'fishsuite'],
    answer: "**FishSuite** è la suite per il settore ittico. Include: tracciabilità lotti, conformità Ministero MIT, integrazione AIS marittimo, monitoraggio satellitare, sensori IoT a bordo. Da €79/mese.",
    tags: ['pesca', 'ittico'],
  },
  {
    id: 'suite-retail',
    category: 'Suite',
    question: "Cos'è RetailSuite?",
    aliases: ['negozio', 'ecommerce', 'retail', 'pos'],
    answer: "**RetailSuite** è la suite per retail ed e-commerce. Include: POS multi-store, e-commerce sincronizzato (Shopify/WooCommerce/Magento), gestione magazzino in tempo reale, fidelity card, pagamenti Stripe/SumUp/Nexi. Da €59/mese.",
    tags: ['retail', 'ecommerce'],
  },
  {
    id: 'suite-rent',
    category: 'Suite',
    question: "Cos'è RentSuite?",
    aliases: ['immobiliare', 'affitto', 'rentsuite', 'property management'],
    answer: "**RentSuite** è la suite per property management. Include: gestione immobili e contratti d'affitto, generazione documenti SIAE/Agenzia Entrate, scadenze pagamenti automatiche, firma digitale contratti. Da €49/mese.",
    tags: ['immobiliare', 'affitto'],
  },
  {
    id: 'suite-tech',
    category: 'Suite',
    question: "Cos'è TechSuite?",
    aliases: ['software house', 'devops', 'techsuite', 'it'],
    answer: "**TechSuite** è la suite per software house e team IT. Include: project management agile/Scrum, ticketing con SLA, time tracking, code review, CI/CD dashboard, integrazione GitHub/GitLab/Bitbucket/Jira. Da €29/mese.",
    tags: ['it', 'devops'],
  },
  {
    id: 'suite-cv',
    category: 'Suite',
    question: "Cos'è il Consulente Virtuale?",
    aliases: ['consulente del lavoro', 'paghe', 'lavoro'],
    answer: "**Consulente Virtuale** è la suite per consulenti del lavoro. Include: paghe e contributi, F24, integrazione INPS/INAIL/Cassa Edile/Agenzia Entrate, scadenze contributive automatiche. Da €69/mese.",
    tags: ['lavoro', 'paghe'],
  },
  {
    id: 'suite-civic',
    category: 'Suite',
    question: "Cos'è CivicCore?",
    aliases: ['pa', 'pubblica amministrazione', 'civiccore', 'caf', 'patronato'],
    answer: "**CivicCore** è la suite per Pubblica Amministrazione, CAF e Patronati. Include: ISEE, modelli fiscali, integrazione INPS/Agenzia Entrate/PagoPA/SPID/CIE, gestione pratiche cittadini, archivio digitale. Da €89/mese.",
    tags: ['pa', 'caf'],
  },
  {
    id: 'suite-pet',
    category: 'Suite',
    question: "Cos'è PetVerse?",
    aliases: ['veterinaria', 'animali', 'petverse', 'clinica veterinaria'],
    answer: "**PetVerse** è la suite per veterinari. Include: cartella clinica animale, anagrafe canina, prenotazioni, vaccinazioni, integrazione Zooplus, fatturazione automatica.",
    tags: ['veterinaria'],
  },
  {
    id: 'suite-archon',
    category: 'Suite',
    question: "Cos'è Archon OS?",
    aliases: ['archon', 'multi-entity', 'gruppo', 'holding'],
    answer: "**Archon OS** è la soluzione per gruppi multi-entity e holding. Coordina più aziende sotto un unico cruscotto, consolidamento dati, governance, audit. Disponibile solo nel piano Enterprise.",
    tags: ['enterprise', 'multi-entity'],
  },
  {
    id: 'suite-list',
    category: 'Suite',
    question: "Quante suite avete?",
    aliases: ['quante verticali', 'lista suite', 'tutte le suite'],
    answer: "Abbiamo **13 suite verticali**: BuildSuite (edilizia), LegalMind (legale), DentalSuite (odontoiatria), FoodSuite (ristorazione), OK Chef (HoReCa), FishSuite (ittico), RetailSuite (retail), RentSuite (immobiliare), TechSuite (IT), Consulente Virtuale (lavoro), CivicCore (PA), PetVerse (veterinaria), Archon OS (multi-entity). Vai su [/suite](/suite) per dettagli.",
    tags: ['suite', 'lista'],
  },
  {
    id: 'suite-multiple',
    category: 'Suite',
    question: "Posso usare più suite contemporaneamente?",
    aliases: ['combinare suite', 'multiple suite', 'più moduli'],
    answer: "Sì. L'architettura è modulare: attivi una suite alla volta o tutte insieme. I dati sono condivisi (un cliente in una suite è disponibile in tutte le altre). Nessuna migrazione, nessun downtime. Il piano Professional include tutte le suite attivabili a scelta.",
    tags: ['suite', 'modulare'],
  },
  {
    id: 'suite-custom',
    category: 'Suite',
    question: "Il mio settore non c'è, potete fare una suite custom?",
    aliases: ['settore custom', 'personalizzata', 'su misura'],
    answer: "Sì, costruiamo suite su misura. Metodo: 1) **Diagnosi** dei tuoi processi, 2) **Migrazione** dati e configurazione moduli, 3) **Operatività** con CoreMind addestrato sul tuo settore. Tempi: 4–12 settimane. Contattaci su [/contatti](/contatti) per una valutazione gratuita.",
    tags: ['custom', 'su misura'],
  },

  // ============ INTEGRAZIONI ============
  {
    id: 'integr-1',
    category: 'Integrazioni',
    question: "Quali integrazioni avete?",
    aliases: ['connettori', 'integrazioni disponibili', 'api', 'collegamenti'],
    answer: "Oltre **200 integrazioni native** tra cui: Fatture in Cloud, Aruba, Teamsystem, Zucchetti, INPS, Agenzia Entrate, INAIL, PagoPA, SPID, AutoCAD, Revit, PriMus, ACCA, Toast, Square, Shopify, WooCommerce, Stripe, Nexi, GitHub, Slack, Microsoft Teams, Google Workspace, e tanti altri. Lista completa su [/integrazioni](/integrazioni).",
    tags: ['integrazioni'],
  },
  {
    id: 'integr-2',
    category: 'Integrazioni',
    question: "Posso integrare il mio software esistente?",
    aliases: ['software custom', 'sistemi esistenti', 'erp esistente'],
    answer: "Sì. Ecosystem si integra via API REST, webhook, file CSV/JSON, database diretto. Per sistemi non standard sviluppiamo connettori custom (incluso nel piano Enterprise, su preventivo per gli altri). Tempi medi: 1–4 settimane.",
    tags: ['api', 'custom'],
  },
  {
    id: 'integr-3',
    category: 'Integrazioni',
    question: "Avete un'API pubblica?",
    aliases: ['api documentation', 'rest api', 'webhook'],
    answer: "Sì: API REST completa, autenticata via OAuth 2.0 o API key, rate-limited, documentata su developer.ecosystem.org. Webhook in real-time per ogni evento (creazione, modifica, eliminazione). SDK ufficiali: TypeScript, Python, PHP.",
    tags: ['api', 'sviluppatori'],
  },
  {
    id: 'integr-4',
    category: 'Integrazioni',
    question: "Posso esportare i miei dati?",
    aliases: ['export', 'estrarre dati', 'scaricare dati', 'csv'],
    answer: "Sì, sempre. Export completo in CSV, JSON, SQL disponibile in qualsiasi momento dalla dashboard. Nessun lock-in: i tuoi dati sono tuoi e li esporti quando vuoi. Per esport batch periodici, configurabile via API.",
    tags: ['export', 'dati'],
  },

  // ============ SUPPORTO ============
  {
    id: 'support-1',
    category: 'Supporto',
    question: "Come funziona il supporto?",
    aliases: ['assistenza', 'help', 'customer care', 'servizio clienti'],
    answer: "I piani **Professional** ed **Enterprise** includono supporto multicanale (email, chat CoreMind, telefono) con SLA contrattuali e ore di assistenza incluse. Il piano **Starter** include email support con SLA 48h. Per esigenze H24/7 c'è il **Supporto Premium** (manager dedicato, risposta 30 minuti) come add-on a +€399/mese.",
    tags: ['supporto', 'sla'],
  },
  {
    id: 'support-2',
    category: 'Supporto',
    question: "Quali sono i tempi di risposta (SLA)?",
    aliases: ['sla', 'tempi di risposta', 'urgenza'],
    answer: "SLA per piano:\n- **Starter**: 48h lavorative (email)\n- **Professional**: 4h lavorative · 8h h24 (multicanale)\n- **Enterprise**: 1h lavorative · 4h h24 con escalation\n- **Premium add-on**: 30 minuti H24/7\n\nLe ore di assistenza non utilizzate non si cumulano tra mesi.",
    tags: ['sla', 'tempi'],
  },
  {
    id: 'support-3',
    category: 'Supporto',
    question: "Fate formazione e onboarding?",
    aliases: ['training', 'formazione', 'corso', 'tutorial', 'onboarding'],
    answer: "Sì. Onboarding incluso in tutti i piani:\n- **Starter**: 4h\n- **Professional**: 16h\n- **Enterprise**: 80h + on-site change management\n\nIncluso: formazione team, importazione dati, configurazione moduli, training CoreMind sul tuo settore. Documentazione + tutorial video sempre accessibili.",
    tags: ['onboarding', 'formazione'],
  },
  {
    id: 'support-4',
    category: 'Supporto',
    question: "C'è un account manager dedicato?",
    aliases: ['account manager', 'referente', 'persona dedicata'],
    answer: "Sì nel piano **Enterprise** (account manager dedicato con reperibilità H24 per critical issues) e nel **Supporto Premium** add-on (+€399/mese, disponibile per Professional ed Enterprise). Manager italiano, contatto diretto via Slack condiviso o telefono.",
    tags: ['enterprise', 'account manager'],
  },
  {
    id: 'support-5',
    category: 'Supporto',
    question: "Quanti utenti possono usare Ecosystem?",
    aliases: ['utenti', 'numero utenti', 'team', 'collaboratori'],
    answer: "Per piano:\n- **Starter**: fino a 5 utenti\n- **Professional**: utenti illimitati\n- **Enterprise**: utenti illimitati multi-tenant\n\nGestione ruoli e permessi granulare. SSO SAML/OIDC nei piani Pro+ ed Enterprise.",
    tags: ['utenti'],
  },

  // ============ SICUREZZA / PRIVACY ============
  {
    id: 'security-1',
    category: 'Sicurezza',
    question: "Come gestite la sicurezza dei dati?",
    aliases: ['sicurezza', 'protezione dati', 'crittografia'],
    answer: "Sicurezza enterprise-grade: TLS 1.3 in transit, AES-256 at-rest, hosting su data center italiani ISO 27001 / ISO 22301 / Tier IV, backup automatici giornalieri con retention 30 giorni (90 Enterprise), penetration test annuale (Enterprise), audit log completo, MFA disponibile, SSO SAML/OIDC.",
    tags: ['sicurezza', 'crittografia'],
  },
  {
    id: 'security-2',
    category: 'Sicurezza',
    question: "Siete conformi al GDPR?",
    aliases: ['gdpr', 'privacy', 'normativa', 'compliance'],
    answer: "Sì, 100% conformi al GDPR. Sviluppo privacy-by-design, DPO interno, registro trattamenti, gestione consensi granulare, diritto di cancellazione/portabilità automatizzato, data residency in Italia. Contratto DPA disponibile per ogni cliente.",
    tags: ['gdpr', 'privacy'],
  },
  {
    id: 'security-3',
    category: 'Sicurezza',
    question: "Dove sono ospitati i miei dati?",
    aliases: ['hosting', 'server', 'cloud', 'data center', 'dove sono i dati'],
    answer: "Hosting di default: data center **italiani** certificati ISO 27001 / ISO 22301 / Tier IV. Cluster PostgreSQL dedicati per cliente. Per Enterprise: scelta del provider (AWS Italia, Azure Italia, OVH Italia) o **on-premise** sui tuoi server. Mai dati fuori dall'UE senza tuo consenso esplicito.",
    tags: ['hosting', 'italia'],
  },
  {
    id: 'security-4',
    category: 'Sicurezza',
    question: "I miei dati sono miei?",
    aliases: ['proprietà dati', 'di chi sono i dati', 'lock-in'],
    answer: "Sì, sempre e solo tuoi. Nessun lock-in: export completo (CSV, JSON, SQL) disponibile quando vuoi. In caso di disdetta hai 90 giorni per scaricare tutto, poi cancellazione definitiva certificata.",
    tags: ['dati', 'proprietà'],
  },
  {
    id: 'security-5',
    category: 'Sicurezza',
    question: "Avete certificazioni di sicurezza?",
    aliases: ['iso 27001', 'soc2', 'certificazioni'],
    answer: "Sì: **ISO 27001** (sicurezza informazione), **ISO 22301** (continuità operativa), **GDPR**. Audit terzi annuali. Penetration test annuale incluso nel piano Enterprise. Conformità settoriali (HACCP, AGIA, MIT) integrate nelle suite verticali.",
    tags: ['certificazioni', 'iso'],
  },
  {
    id: 'security-6',
    category: 'Sicurezza',
    question: "Cosa succede se Ecosystem chiude?",
    aliases: ['business continuity', 'fallimento', 'continuity'],
    answer: "Tutela contrattuale: codice sorgente in escrow notarile, dati esportabili in standard aperti (PostgreSQL, JSON, CSV), diritto di accesso al codice in caso di chiusura aziendale. Inoltre Ecosystem è certificata ISO 22301 (continuità operativa).",
    tags: ['business continuity'],
  },

  // ============ TECNICO ============
  {
    id: 'tech-1',
    category: 'Tecnico',
    question: "Su quale tecnologia gira Ecosystem?",
    aliases: ['stack', 'tecnologia', 'tech stack', 'architettura'],
    answer: "Stack moderno: backend Node.js/TypeScript + Python (per AI/ML), database PostgreSQL multi-tenant, frontend React + Next.js, orchestrazione Kubernetes, AI orchestration custom basata su LangChain/LlamaIndex. 393 tabelle DB produttive. Microservizi event-driven.",
    tags: ['tecnologia', 'stack'],
  },
  {
    id: 'tech-2',
    category: 'Tecnico',
    question: "Devo installare qualcosa?",
    aliases: ['installazione', 'download', 'software da installare'],
    answer: "No. Ecosystem è **SaaS**: accedi da browser (Chrome, Firefox, Safari, Edge), nessuna installazione. App mobile iOS/Android disponibile per le suite operative. Per Enterprise: on-premise installato dal nostro team sui tuoi server.",
    tags: ['saas', 'browser'],
  },
  {
    id: 'tech-3',
    category: 'Tecnico',
    question: "Funziona da mobile?",
    aliases: ['mobile', 'smartphone', 'app', 'ios', 'android'],
    answer: "Sì. Web app responsive completa da smartphone. App nativa iOS/Android per le suite operative (BuildSuite cantiere, FoodSuite cucina, RetailSuite POS, DentalSuite agenda). Sync real-time con cloud.",
    tags: ['mobile', 'app'],
  },
  {
    id: 'tech-4',
    category: 'Tecnico',
    question: "Funziona offline?",
    aliases: ['offline', 'senza connessione', 'no internet'],
    answer: "Le app mobile native (BuildSuite, FoodSuite, RetailSuite, DentalSuite) funzionano offline e si sincronizzano quando torna la connessione. Web app richiede connessione (caching parziale).",
    tags: ['offline', 'sync'],
  },
  {
    id: 'tech-5',
    category: 'Tecnico',
    question: "Quanto è veloce?",
    aliases: ['performance', 'velocità', 'lentezza'],
    answer: "Performance enterprise: 99.9% uptime SLA Enterprise, latency media <200ms, query CoreMind <1.5s, page load <1s. Architettura horizontally-scalable, CDN, caching multi-layer. Monitorato 24/7 con dashboard pubblica.",
    tags: ['performance'],
  },
  {
    id: 'tech-6',
    category: 'Tecnico',
    question: "Quanti dati posso archiviare?",
    aliases: ['storage', 'spazio', 'gb', 'archiviazione'],
    answer: "Storage incluso per piano:\n- **Starter**: 25 GB\n- **Professional**: 250 GB\n- **Enterprise**: illimitato\n\nDocumenti, foto, allegati, backup compresi. Storage extra a €0.05/GB/mese.",
    tags: ['storage'],
  },
  {
    id: 'tech-7',
    category: 'Tecnico',
    question: "Posso fare backup manuali?",
    aliases: ['backup', 'salvataggio', 'ripristino'],
    answer: "Sì. Backup automatici giornalieri (retention 30 giorni Starter/Pro, 90 Enterprise) + backup manuale on-demand dalla dashboard, in formato standard (PostgreSQL dump). Disaster recovery con RTO <1h, RPO <15min nel piano Enterprise.",
    tags: ['backup'],
  },

  // ============ IMPLEMENTAZIONE ============
  {
    id: 'impl-1',
    category: 'Implementazione',
    question: "Quanto tempo serve per partire?",
    aliases: ['onboarding', 'implementazione', 'go live', 'attivazione', 'tempi'],
    answer: "Tempi medi:\n- **Starter**: 1–2 settimane (configurazione + import + formazione 4h)\n- **Professional**: 2–4 settimane (più moduli, integrazioni, training 16h)\n- **Enterprise**: 6–12 settimane (custom, on-premise, change management 80h+)\n\nGo-live progressivo: prima il modulo critico, poi gli altri.",
    tags: ['onboarding', 'tempi'],
  },
  {
    id: 'impl-2',
    category: 'Implementazione',
    question: "Posso migrare dati dal mio gestionale attuale?",
    aliases: ['migrazione', 'import dati', 'spostare dati'],
    answer: "Sì, sempre incluso nel setup. Importiamo da: Excel/CSV, MySQL/PostgreSQL/MSSQL, gestionali italiani (Teamsystem, Zucchetti, Aruba, Fatture in Cloud), API. Per dati legacy non standard: import manuale o connettori custom (incluso Enterprise). Verifica integrità + reconciliation con il tuo team.",
    tags: ['migrazione'],
  },
  {
    id: 'impl-3',
    category: 'Implementazione',
    question: "Chi configura Ecosystem per la mia azienda?",
    aliases: ['configurazione', 'chi setta', 'setup'],
    answer: "Il team di onboarding di Ecosystem. Procedura: kick-off call → mappatura processi → configurazione moduli → import dati → training team → go-live assistito. Il setup è una tantum (€490 Starter — €80K Enterprise).",
    tags: ['setup', 'onboarding'],
  },

  // ============ FATTURAZIONE ============
  {
    id: 'billing-1',
    category: 'Fatturazione',
    question: "Come pago?",
    aliases: ['metodo di pagamento', 'pagare', 'modalità pagamento'],
    answer: "Metodi accettati:\n- **Bonifico bancario** (default)\n- **Carta di credito/debito** (Visa, Mastercard, AmEx)\n- **SEPA Direct Debit** (addebito automatico)\n- **Stripe** per pagamenti ricorrenti\n\nFatturazione mensile/trimestrale/annuale (-10%). Fattura elettronica B2B inclusa.",
    tags: ['pagamento'],
  },
  {
    id: 'billing-2',
    category: 'Fatturazione',
    question: "Posso disdire quando voglio?",
    aliases: ['disdetta', 'cancellare contratto', 'recesso'],
    answer: "Disdetta libera dopo i primi 12 mesi con preavviso di 60 giorni. Nei primi 12 mesi vincolo contrattuale per ammortizzare il setup. Per Enterprise contratti pluriennali con clausole personalizzate.",
    tags: ['disdetta'],
  },
  {
    id: 'billing-3',
    category: 'Fatturazione',
    question: "Mandate fattura elettronica?",
    aliases: ['fattura elettronica', 'sdi', 'codice destinatario'],
    answer: "Sì, fatturazione elettronica B2B via SDI inclusa. Inseriamo il tuo codice destinatario o PEC nel contratto. Fattura mensile entro il 5 del mese successivo. PDF disponibile anche dal portale cliente.",
    tags: ['fattura'],
  },

  // ============ FREQUENT ACTIONS ============
  {
    id: 'action-1',
    category: 'Azioni',
    question: "Come creo un nuovo cliente?",
    aliases: ['nuovo cliente', 'aggiungere cliente', 'crea cliente'],
    answer: "In Ecosystem dici a CoreMind: 'Crea cliente Mario Rossi P.IVA 12345678901, email mario@example.it'. CoreMind compila scheda automaticamente con dati anagrafici, fiscali, recapiti. Oppure dal menu Clienti → Nuovo. Cliente subito disponibile in tutte le suite attive.",
    tags: ['cliente', 'crud'],
  },
  {
    id: 'action-2',
    category: 'Azioni',
    question: "Come emetto una fattura?",
    aliases: ['fatturare', 'fattura cliente', 'creare fattura'],
    answer: "Tre modi:\n1. **CoreMind**: 'Fatturalo Mario Rossi 1.500€ per consulenza marzo'\n2. **Da pratica/cantiere/ordine**: pulsante 'Fattura' (genera dai dati esistenti)\n3. **Manuale**: menu Fatture → Nuova\n\nFattura elettronica generata e inviata via SDI in automatico. Pagamenti tracciati con riconciliazione bancaria.",
    tags: ['fattura', 'azioni'],
  },
  {
    id: 'action-3',
    category: 'Azioni',
    question: "Come vedo i miei KPI?",
    aliases: ['kpi', 'dashboard', 'metriche', 'analytics'],
    answer: "Dashboard principale all'apertura: revenue, MRR, churn, top clienti, alert critici, trend. Dashboard verticali per ogni suite (es. BuildSuite mostra cantieri attivi, margini, SAL pending). CoreMind risponde a: 'Fatturato Q3 vs Q2', 'Top 10 clienti per margine', 'Cantieri in ritardo'.",
    tags: ['dashboard', 'kpi'],
  },

  // ============ COMPETITIVI ============
  {
    id: 'comp-1',
    category: 'Competitivi',
    question: "Cosa vi differenzia da SAP, Zucchetti, Teamsystem?",
    aliases: ['differenze', 'concorrenti', 'rispetto altri', 'sap', 'zucchetti', 'teamsystem'],
    answer: "Differenze chiave:\n- **AI nativa**: CoreMind in ogni funzione, non bolt-on\n- **Multi-verticale unificata**: 13 suite con dati condivisi (loro hanno verticali separate)\n- **Cloud-native moderno**: stack 2024+ (loro spesso legacy)\n- **Trasparenza prezzi**: prezzi pubblici, niente preventivi opachi\n- **Onboarding 1-4 settimane** (loro 3-12 mesi)\n- **Dimensioni**: ottimizzati per PMI italiane (loro grandi enterprise)",
    tags: ['concorrenti'],
  },
  {
    id: 'comp-2',
    category: 'Competitivi',
    question: "Posso integrare Ecosystem con il mio gestionale attuale?",
    aliases: ['affiancare', 'integrazione esistente', 'in parallelo'],
    answer: "Sì, lavoriamo bene in coesistenza. Esempio: tieni Teamsystem per la contabilità, usi BuildSuite per i cantieri, dati sincronizzati via API. Migrazione completa è opzionale, possiamo vivere accanto al tuo software esistente. Setup integrazione incluso nel preventivo.",
    tags: ['integrazione', 'coesistenza'],
  },
]

/**
 * Convenience: lookup table by id
 */
export const KB_BY_ID: Map<string, KBEntry> = new Map(
  KNOWLEDGE_BASE.map((e) => [e.id, e])
)
